spring.application.name=auth-code-flow
server.port=8089

# oauth2 client config
# username and password of our app for keycloak OAuth server
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.client-id=oauth2-authorization-code-flow
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.client-secret=dnBHO52iPhGFmvA0y3TjDBId4fohEuHB

# scope means what access we want
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.scope=openid,profile,roles,email
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.authorization-grant-type=authorization_code

# this is keycloak realm
spring.security.oauth2.client.provider.oauth2-authorization-code-flow.issuer-uri=http://127.0.0.1:8443/realms/oauth2-demos

# this is the uri where keycloak will send users back to after login
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.redirect-uri=http://localhost:8089/login/oauth2/code/oauth2-authorization-code-flow
