spring.application.name=configdemo
server.port=8081

build.id=122
build.version=2.2.2
build.name="Default-Build"
build.type="Default Build"

spring.profiles.active=dev

# if config server is down use the default properties mentioned in the service, to that is why
# config server is set as optional.
spring.config.import=optional:configserver:http://localhost:8888

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

management.endpoints.web.exposure.include=*