spring.application.name=producer

server.port=8089

spring.kafka.producer.bootstrap-servers=localhost:9092

# serialization to send objects to kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

# Configuration for Spring cloud function, we are exposing the function as a rest endpoint
# at /uppercase endpoint. We defined the function inside FunctionsClass.
spring.cloud.function.definition=uppercase
spring.cloud.function.web.path=/uppercase
spring.cloud.function.web.type=rest
spring.cloud.function.web.method=POST

# Configuration for Spring cloud stream.
# tells spring which function we are using for publish message that is sendRiderLocation.
spring.cloud.stream.function.definition=sendRiderLocation

# tells spring which topic we are using for publish message that is my-topic-new.
spring.cloud.stream.bindings.sendRiderLocation-out-0.destination=my-topic-new

# tells spring which content type we are using for publish message that is application/json.
spring.cloud.stream.bindings.sendRiderLocation-out-0.content-type=application/json

spring.cloud.kafka.binder.brokers=localhost:9092





